### ISSUE TITLE
Problemas e melhoria da plataforma

### ISSUE THREAD

**Issue by rafaelcn** [rafaelcn/SCE#13]
# Coisas para fazer

### Ferramentas do SCE: 
- [X]  Desenvolver as ferramentas para visualização de perfis.
- [X] Finalizar conteúdo da página de ajuda. 
  - [X] Cadastrar/remover estagiário. ae2e5f2
  - [X] Erros da aplicação. ae2e5f2
  - [X] Configuração da aplicação (empresas, turmas e orientadores) ae2e5f2
 -  [X] Como visualizar informações de uma entidade. 

### Design
- [X] Mover o menu da aplicação para o topo ao invés de usar o `link-group`, ganhando assim mais espaço na tela. 28cc6e5  
- [X] Redesenhar página de ajuda. 73f7a6c
- [X] Criar página para a visualização e edição das entidades do sistema. 9452fbe
  - [X] página de perfil de estagiário. 
  - [X] página de perfil de orientador.
  - [X] página de perfil da empresa.
  - [X] página de perfil da turma.

**Comment by ryukinix** [comment]
Super cry

**Comment by rafaelcn** [comment]
We'r kinda of close @ryukinix!

**Comment by ryukinix** [comment]
NICE

**Comment by rafaelcn** [comment]
@tatyanebianchi temos que terminar a ajuda! :cry:

**Comment by rafaelcn** [comment]
A função de edição não vai estar disponível no sistema (pelo menos não nessa versão) pois eu vou ter que modificar o banco de dados e reimplementar quase tudo que existe no sistema.  E a **deadline** está bem aqui. :-1:

**Comment by rafaelcn** [comment]
Holy moly, got it @ryukinix, after dropping some functions and coding like a beast this night hahaha. **JS HELL**. :tada:
