### ISSUE TITLE
Classe da citação padrão não está com cor de background

### ISSUE THREAD

**Issue by tatyanebianchi** [rafaelcn/SCE#14]
Para reproduzir o erro basta escrever esse pequeno pedaço de código em qualquer página HTML do sistema:

```
<blockquote class="quote quote-defaulf">
    <a href="https://pt.wikipedia.org/wiki/HTTP_404">Erro 404</a>
</blockquote>
```

**Comment by rafaelcn** [comment]
Na verdade a classe default da citação tem um background sim. Só olhar [aqui](https://github.com/rafaelcn/SCE/blob/master/src/public/css/sce/sce.css#L274-L277). 

```
.quote-default {
  border-left: 3px solid rgb(195, 195, 195) !important;
  background: rgba(195, 195, 195, .2);
}
```
